[project]
name = "recommendation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "numpy>=2.2.6",
    "scikit-learn>=1.6.1",
]
